---
- name: Deploy Cnf Operators
  hosts: localhost
  become: yes
  environment:
    PATH: "/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/root/bin"
  roles:
  - cluster-setup
  - performance
#  - cnv
  - ptp
  - sctp
  - sriov
  - dpdk
