all:
  vars:
   performance_channel: 4.4
   mcps:
   - worker-cnf
   - master-cnf
   performance_crs:
   -    |
       apiVersion: performance.openshift.io/v1alpha1
       kind: PerformanceProfile
       metadata:
         name: performance
       spec:
         cpu:
           isolated: "1-3"
           reserved: "0"
         hugepages:
           defaultHugepagesSize: "1G"
           pages:
           - size: "1G"
             count: 1
         realTimeKernel:
           enabled: true
         nodeSelector:
           node-role.kubernetes.io/worker-cnf: ""
  children:
      nodes:
        hosts:
          node01:
            role: worker-cnf
          node02:
            role: worker-cnf
