- name: Store rendered yamls as variables
  set_fact:
    namespace: '{{ lookup("file", "files/namespace.yml") }}'
    operatorgroup: '{{ lookup("template", "templates/operatorgroup.yml.j2") }}'
    subscription: '{{ lookup("template", "templates/subscription.yml.j2") }}'
    cr: '{{ lookup("template", "templates/cr.yml.j2") }}'
    mcp_pool: '{{ lookup("template", "templates/mcp.yml.j2") }}'

- name: Deploy yamls
  shell: "echo -n '{{ item }}' | oc apply -f -"
  with_items:
  - "{{ namespace }}"
  - "{{ operatorgroup }}"
  - "{{ subscription }}"
  - "{{ cr }}"
  - "{{ mcp_pool }}"
