- name: Store rendered yamls as variables
  set_fact:
    install: '{{ lookup("template", "templates/install.yml.j2") }}'

- name: Install
  shell: "echo -n '{{ install }}' | oc apply -f -"

- name: Wait to avoid race conditions
  pause:
    seconds: 5

- name: Wait for operator to be up
  shell: "oc wait --for=condition=Ready pod -l name=performance-operator -n openshift-performance-addon"

- name: Customize
  shell: "echo -n '{{ item }}' | oc apply -f -"
  with_items: "{{ performance_crs }}"
