- name: Store rendered yamls as variables
  set_fact:
    install: '{{ lookup("template", "templates/install.yml.j2") }}'
    cr: '{{ lookup("template", "templates/cr.yml.j2") }}'
    mcp_pool: '{{ lookup("template", "templates/mcp.yml.j2") }}'

- name: Install
  shell: "echo -n '{{ install }}' | oc apply -f -"

- name: Customize
  shell: "echo -n '{{ item }}' | oc apply -f -"
  with_items:
  - "{{ cr }}"
  - "{{ mcp_pool }}"
