- name: Tag nodes as per inventory
  command: "{{ item }}"
  ignore_errors: yes
  with_items: "{{ hostvars | oclabels }}"
- name: Create machineconfigpools as per inventory
  shell: |
    echo -n 'apiVersion: machineconfiguration.openshift.io/v1
    kind: MachineConfigPool
    metadata:
      name: {{ item }}
      labels:
        machineconfiguration.openshift.io/role: {{ item }}
    spec:
      machineConfigSelector:
        matchExpressions:
          - {
              key: machineconfiguration.openshift.io/role,
              operator: In,
              values: [{{ item }}, worker],
            }
      paused: true
      nodeSelector:
        matchLabels:
          node-role.kubernetes.io/{{ item }}: ""' | oc apply -f -
  with_items: "{{ mcps }}"
#- meta: end_play
