- name: Store rendered yamls as variables
  set_fact:
    sriov_networknodepolicy_dpdk: '{{ lookup("template", "templates/sriov-networknodepolicy-dpdk.yml.j2") }}'
    scc: '{{ lookup("template", "templates/scc.yml.j2") }}'
    buildconfig: '{{ lookup("template", "templates/build-config.yml.j2") }}'
    deploymentconfig: '{{ lookup("template", "templates/deployment-config.yml.j2") }}'
    dpdknetwork: '{{ lookup("template", "templates/dpdk-network.yml.j2") }}'

- name: Deploy yamls
  shell: "echo -n '{{ item }}' | oc apply -f -"
  with_items:
  - "{{ sriov_networknodepolicy_dpdk }}"
  - "{{ scc }}"
  - "{{ dpdknetwork }}"
  - "{{ buildconfig }}"
  - "{{ deploymentconfig }}"
