- name: Store rendered yamls as variables
  set_fact:
    namespace: '{{ lookup("template", "templates/namespace.yml.j2") }}'
    operatorgroup: '{{ lookup("template", "templates/operatorgroup.yml.j2") }}'
    subscription: '{{ lookup("template", "templates/subscription.yml.j2") }}'

- name: Deploy yamls
  shell: "echo -n '{{ item }}' | oc apply -f -"
  with_items:
  - "{{ namespace }}"
  - "{{ operatorgroup }}"
  - "{{ subscription }}"
